name: Nimbus nim-beacon-chain CI
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        target:
          # Unit tests
          - os: linux
            cpu: amd64
            TEST_KIND: unit-tests
          - os: linux
            cpu: i386
            TEST_KIND: unit-tests
          - os: macos
            cpu: amd64
            TEST_KIND: unit-tests
          - os: windows
            cpu: amd64
            TEST_KIND: unit-tests
          # Devel cache corrupted for mingw? missing propidl.h on PR but not push CI
          # - os: windows
          #   cpu: i386
          #   TEST_KIND: unit-tests

          # # Minimal integration tests
          # - os: linux
          #   cpu: amd64
          #   TEST_KIND: finalization-minimal
          # - os: linux
          #   cpu: i386
          #   TEST_KIND: finalization-minimal
          # # Requires GNU getopt
          # - os: macos
          #   cpu: amd64
          #   TEST_KIND: finalization-minimal
          # - os: windows
          #   cpu: amd64
          #   TEST_KIND: finalization-minimal
          # # TODO - Bootstrap issue: https://github.com/status-im/nim-beacon-chain/issues/1725
          # # - os: windows
          # #   cpu: i386
          # #   TEST_KIND: finalization-minimal

          # Mainnet integration tests
          # - os: linux
          #   cpu: amd64
          #   TEST_KIND: finalization-mainnet
          # # - os: linux
          # #   cpu: i386
          # #   TEST_KIND: finalization-mainnet
          # # - os: macos
          # #   cpu: amd64
          # #   TEST_KIND: finalization-mainnet
          # - os: windows
          #   cpu: amd64
          #   TEST_KIND: finalization-mainnet
          # # TODO - Bootstrap issue: https://github.com/status-im/nim-beacon-chain/issues/1725
          # # - os: windows
          # #   cpu: i386
          # #   TEST_KIND: finalization-mainnet
        include:
          - target:
              os: linux
            builder: ubuntu-18.04
          - target:
              os: macos
            builder: macos-10.15
          - target:
              os: windows
            builder: windows-2019
    name: '${{ matrix.target.os }}-${{ matrix.target.cpu }} (${{ matrix.target.TEST_KIND }})'
    runs-on: ${{ matrix.builder }}
    steps:
      - name: Get branch name
        shell: bash
        run: |
          if [[ '${{  github.event_name }}' == 'pull_request' ]]; then
            echo "##[set-output name=branch_name;]$(echo ${GITHUB_HEAD_REF})"
            echo "Branch found (PR): ${GITHUB_HEAD_REF}"
          else
            echo "##[set-output name=branch_name;]$(echo ${GITHUB_REF#refs/heads/})"
            echo "Branch found (not PR): ${GITHUB_REF#refs/heads/}"
          fi
        id: get_branch

      - name: Cancel Previous Runs (except master/devel)
        if: >
          steps.get_branch.outputs.branch_name != 'master' &&
          steps.get_branch.outputs.branch_name != 'devel'
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout nim-beacon-chain
        uses: actions/checkout@v2
        with:
          path: nim-beacon-chain

      - name: Derive environment variables
        shell: bash
        run: |
          if [[ '${{ matrix.target.cpu }}' == 'amd64' ]]; then
            ARCH=64
            PLATFORM=x64
          else
            ARCH=32
            PLATFORM=x86
          fi
          echo "::set-env name=ARCH::$ARCH"
          echo "::set-env name=PLATFORM::$PLATFORM"

          # libminiupnp / natpmp
          if [[ '${{ runner.os }}' == 'Linux' && '${{ matrix.target.cpu }}' == 'i386' ]]; then
            export CFLAGS="${CFLAGS} -m32"
            echo "::set-env name=CFLAGS::$CFLAGS"
          fi
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Install build dependencies (Linux i386)
        if: runner.os == 'Linux' && matrix.target.cpu == 'i386'
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-fast update -qq
          sudo DEBIAN_FRONTEND='noninteractive' apt-fast install \
            --no-install-recommends -yq gcc-multilib g++-multilib
          mkdir -p external/bin
          cat << EOF > external/bin/gcc
          #!/bin/bash
          exec $(which gcc) -m32 "\$@"
          EOF
          cat << EOF > external/bin/g++
          #!/bin/bash
          exec $(which g++) -m32 "\$@"
          EOF
          chmod 755 external/bin/gcc external/bin/g++
          echo '::add-path::${{ github.workspace }}/external/bin'
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Restore MinGW-W64 (Windows) from cache
        if: runner.os == 'Windows'
        id: windows-mingw-cache
        uses: actions/cache@v2
        with:
          path: external/mingw-${{ matrix.target.cpu }}
          key: 'mingw-${{ matrix.target.cpu }}'

      - name: Restore Nim DLLs dependencies (Windows) from cache
        if: runner.os == 'Windows'
        id: windows-dlls-cache
        uses: actions/cache@v2
        with:
          path: external/dlls-${{ matrix.target.cpu }}
          key: 'dlls-${{ matrix.target.cpu }}'

      - name: Install MinGW64 dependency (Windows)
        if: >
          steps.windows-mingw-cache.outputs.cache-hit != 'true' &&
          runner.os == 'Windows'
        shell: bash
        run: |
          mkdir -p external
          curl -L "https://nim-lang.org/download/mingw$ARCH-6.3.0.7z" -o "external/mingw-${{ matrix.target.cpu }}.7z"
          7z x -y "external/mingw-${{ matrix.target.cpu }}.7z" -oexternal/
          mv external/mingw$ARCH external/mingw-${{ matrix.target.cpu }}

      - name: Install DLLs dependencies (Windows)
        if: >
          steps.windows-dlls-cache.outputs.cache-hit != 'true' &&
          runner.os == 'Windows'
        shell: bash
        run: |
          mkdir -p external
          curl -L "https://nim-lang.org/download/windeps.zip" -o external/windeps.zip
          7z x -y external/windeps.zip -oexternal/dlls-${{ matrix.target.cpu }}

      - name: Path to cached dependencies (Windows)
        if: >
          runner.os == 'Windows'
        shell: bash
        run: |
          echo '::add-path::${{ github.workspace }}'"/external/mingw-${{ matrix.target.cpu }}/bin"
          echo '::add-path::${{ github.workspace }}'"/external/dlls-${{ matrix.target.cpu }}"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Install build dependencies (MacOS)
        if: runner.os == 'macOS'
        shell: bash
        run: |
          brew install gnu-getopt
          brew link --force gnu-getopt

      - name: Get latest nimbus-build-system commit hash
        id: versions
        shell: bash
        run: |
          getHash() {
            git ls-remote "https://github.com/$1" "${2:-HEAD}" | cut -f 1
          }
          # nimHash=$(getHash nim-lang/Nim '${{ matrix.branch }}')
          # csourcesHash=$(getHash nim-lang/csources)
          # echo "::set-output name=nim::$nimHash"
          # echo "::set-output name=csources::$csourcesHash"
          nbsHash=$(getHash status-im/nimbus-build-system)
          echo "::set-output name=nimbus_build_system::$nbsHash"

      - name: Restore prebuilt Nim binaries from cache
        id: nim-cache
        uses: actions/cache@v2
        with:
          path: nim-beacon-chain/NimBinaries
          key: 'nim-${{ matrix.target.os }}-${{ matrix.target.cpu }}-${{ steps.versions.outputs.nimbus_build_system }}'

      - name: Build Nim and NBC dependencies
        shell: bash
        working-directory: nim-beacon-chain
        run: |
          ncpu=
          ext=
          case '${{ runner.os }}' in
          'Linux')
            ncpu=$(nproc)
            ;;
          'macOS')
            ncpu=$(sysctl -n hw.ncpu)
            ;;
          'Windows')
            ncpu=$NUMBER_OF_PROCESSORS
            ext=.exe
            ;;
          esac
          [[ -z "$ncpu" || $ncpu -le 0 ]] && ncpu=1
          echo "::set-output name=ncpu::$ncpu"

          make -j$ncpu ARCH_OVERRIDE=$PLATFORM CI_CACHE=NimBinaries V=1 update

      - name: Get latest fixtures commit hash
        if: matrix.target.TEST_KIND == 'unit-tests'
        id: fixtures_version
        shell: bash
        run: |
          getHash() {
            git ls-remote "https://github.com/$1" "${2:-HEAD}" | cut -f 1
          }
          fixturesHash=$(getHash status-im/nim-eth2-scenarios)
          echo "::set-output name=fixtures::$fixturesHash"

      - name: Restore Ethereum Foundation fixtures from cache
        if: matrix.target.TEST_KIND == 'unit-tests'
        id: fixtures-cache
        uses: actions/cache@v2
        with:
          path: nim-beacon-chain/fixturesCache
          key: 'eth2-scenarios-${{ steps.fixtures_version.outputs.fixtures }}'

      # Important: even with a cache hit, this should be run
      # as it symlinks the cached items in their proper place
      - name: Get the Ethereum Foundation fixtures
        if: matrix.target.TEST_KIND == 'unit-tests'
        shell: bash
        working-directory: nim-beacon-chain
        run: |
          scripts/setup_official_tests.sh fixturesCache

      - name: Smoke test the Beacon Node and Validator Client with all tracing enabled
        if: matrix.target.TEST_KIND == 'unit-tests'
        shell: bash
        working-directory: nim-beacon-chain
        run: |
          make -j$ncpu ARCH_OVERRIDE=$PLATFORM LOG_LEVEL=TRACE NIMFLAGS="-d:testnet_servers_image" nimbus_beacon_node
          make -j$ncpu ARCH_OVERRIDE=$PLATFORM LOG_LEVEL=TRACE NIMFLAGS="-d:testnet_servers_image" nimbus_validator_client

      - name: Run nim-beacon-chain tests
        if: matrix.target.TEST_KIND == 'unit-tests'
        shell: bash
        working-directory: nim-beacon-chain
        run: |
          make -j$ncpu ARCH_OVERRIDE=$PLATFORM DISABLE_TEST_FIXTURES_SCRIPT=1 test

      - name: Run nim-beacon-chain testnet0 (minimal)
        if: matrix.target.TEST_KIND == 'finalization-minimal'
        shell: bash
        working-directory: nim-beacon-chain
        run: |
          ./scripts/launch_local_testnet.sh --testnet 0 --nodes 4 --stop-at-epoch 5 --log-level DEBUG --disable-htop --enable-logtrace --data-dir local_testnet0_data --base-port $(( 9000 + EXECUTOR_NUMBER * 100 )) --base-rpc-port $(( 7000 + EXECUTOR_NUMBER * 100 )) --base-metrics-port $(( 8008 + EXECUTOR_NUMBER * 100 )) -- --verify-finalization --discv5:no

      - name: Run nim-beacon-chain testnet1 (mainnet)
        if: matrix.target.TEST_KIND == 'finalization-mainnet'
        shell: bash
        working-directory: nim-beacon-chain
        run: |
          ./scripts/launch_local_testnet.sh --testnet 1 --nodes 4 --stop-at-epoch 5 --log-level DEBUG --disable-htop --enable-logtrace --data-dir local_testnet0_data --base-port $(( 9000 + EXECUTOR_NUMBER * 100 )) --base-rpc-port $(( 7000 + EXECUTOR_NUMBER * 100 )) --base-metrics-port $(( 8008 + EXECUTOR_NUMBER * 100 )) -- --verify-finalization --discv5:no
